addons:
  apt:
    packages:
      - google-chrome-stable
    sources:
      - google-chrome
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
branches:
  only:
  - master
cache:
  directories:
    - ./node_modules/
    - ./third_party/
    - ./tools/
dist: trusty
install: true
script:
- bash scripts/run_karma_tests.sh --single-run
sudo: required
